# Generated by Django 4.1.3 on 2023-01-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productcgallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCGallery',
            new_name='ProductGallery',
        ),
    ]
